### ISSUE TITLE
Input variables provided with "with" are ignored

### ISSUE THREAD

**Issue by khitrenovich** [softprops/turnstyle#1]
I wasn't able to make `poll-interval-seconds` work when provided as input variable - 
```
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It worked for me when I set it as environment variable, though - 
```
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_POLL_INTERVAL_SECONDS: 10
```

I suspect that Actions documentation about how they transform inputs to environment variables is outdated or incorrect. For example, I see that their own `setup-node` action reads input via `core.getInput()` and not from environment variables - https://github.com/actions/setup-node/blob/master/src/setup-node.ts#L12.
