### ISSUE TITLE
Clarification for abort-after-seconds

### ISSUE THREAD

**Issue by ltamrazov** [softprops/turnstyle#27]
Hi, I wanted to clarify how this feature works. I tried to do `abort-after-seconds: 1` hoping to bail right away if there is already a job in progress, but it seemed to wait much longer ~42 seconds before I canceled the job. 

I then though that maybe it needs to work with `poll-interval-seconds`, and also set that to `1`. This time the job resumed although there was already a run in progress so it should have stopped. Screenshot:

![Screen Shot 2020-11-21 at 6 44 31 PM](https://user-images.githubusercontent.com/6433656/99890090-bf517500-2c29-11eb-99c0-aff36bcb2c64.png)

Similarly for the second run that I expected to fail:
![Screen Shot 2020-11-21 at 6 46 47 PM](https://user-images.githubusercontent.com/6433656/99890113-08a1c480-2c2a-11eb-9c79-e6553aebe978.png)

Thank you!

**Comment by ltamrazov** [comment]
This is the workflow:

```yaml
name: release

on:
  pull_request:
    branches: [ master ]

jobs:
  cancel-previous-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Block concurrent deploys
        uses: softprops/turnstyle@v1
        with:
            abort-after-seconds: 1
            poll-interval-seconds: 1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  another-job:
    runs-on: ubuntu-latest
    needs: [cancel-previous-workflows]
    steps:
      - name: sleep
        run: sleep 30
```

**Comment by ltamrazov** [comment]
Further testing seems like it only works when its on the same job like:

```
jobs:
  cancel-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Block concurrent deploys
        uses: softprops/turnstyle@v1
        with:
            abort-after-seconds: 1
            poll-interval-seconds: 1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sleep
        run: sleep 180
```
