### ISSUE TITLE
[Feature Request] Use GITHUB_TOKEN as default

### ISSUE THREAD

**Issue by qoomon** [softprops/turnstyle#60]
Would be  nice if this action would make use of default inputs to pass github token to keep this action as lean as possible.
`action.yaml`
```yaml
inputs: 
  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
```
